const A=document.querySelector('#app'),M=document.querySelector('#modal');let S={r:'discover',login:false};const C={initiative:['יוזמה · פתח תקווה','מחפשות עוד 2–3 משפחות לבקרים משותפים','שתי אמהות לילדים בני 1.5–3 רוצות להתחיל רוטציה פעמיים בשבוע.'],place:['מקום · הוד השרון','סטודיו פנוי בבקרים עם חצר קטנה','פתוח לקבוצה קבועה.'],offer:['שירות מקצועי · Online','עזרה בסטטיסטיקה לסטודנטיות','עזרה מקצועית מרחוק.'],job:['משרה · Hybrid','Research Operations · 60%','גמישות ושילוב בית.']};
const H=(a,b,c='')=>`<p class="eyebrow">${a}</p><h1>${b}</h1>${c?`<p class="lede">${c}</p>`:''}`,B=(x,r)=>`<button class="primary" data-r="${r||''}">${x} <span>←</span></button>`;
function card(k){let c=C[k];return `<article class="card ${k==='initiative'?'featured':''}"><span class="context">${c[0]}</span><h2>${c[1]}</h2><p>${c[2]}</p><div class="signals"><span>מתאים להורים</span><span>${k==='job'?'חלקית':'אזור כללי'}</span></div>${B('לפרטים',k==='job'?'job':k+'-detail')}</article>`}
function page(){let r=S.r,x='';if(r==='discover')x=`<section class="intro">${H('קהילה שמפנה מקום לשני הצדדים','גם לעבוד.<br><em>גם להיות קרובים.</em>','להמשיך לעבוד, ללמוד ולהתפתח — תוך קרבה לילדים.')}${B('מה יעזור לך עכשיו?','start')}</section><nav class="filters"><button class="filter active">הכול</button><button class="filter" data-r="inspiration">השראה</button><button class="filter" data-r="search">עבודה והתפתחות</button></nav><section class="feed"><div style="grid-column:span 7">${card('initiative')}</div><div class="split-cards"><div class="place">${card('place')}</div><div class="care">${card('offer')}</div></div>${card('job')}<article class="action-card">${H('לא מצאת עדיין?','ספרי מה יעזור לך — ונחפש.')}${B('להתחיל לחפש','search')}</article></section>`;
else if(r==='inspiration')x=`<section class="intro">${H('ספריית מודלים','איך גם וגם יכול להיראות?','רעיונות קטנים שאפשר להתחיל מהם.')}</section><section class="feed"><article class="inspiration-card">${H('מודל 01','גם שתי משפחות זה מספיק.','אפשר בבית או בפארק, בלי מקום קבוע ובלי צוות.')}${B('לראות את המודל','model')}</article>${card('place')}</section>`;
else if(r==='model')x=`<section class="intro">${H('מודל השראה','שתי משפחות, רוטציה בבית','כל אחת מקבלת זמן עבודה וגם לוקחת חלק בשמירה על הילדים.')}${B('להתחיל משהו כזה','create-initiative')}</section><article class="card"><h2>איך זה עובד?</h2><p>קובעות ימים קבועים ומתחילות קטן. אין צורך במקום קבוע.</p></article>`;
else if(r==='search')x=`<section class="intro">${H('חיפוש','מה את מחפשת עכשיו?','החיפוש חד־פעמי. רק אם תבחרי, נשמור או נפרסם אותו.')}${B('להתחיל לענות על כמה שאלות','questions')}</section><article class="card"><h2>אפשר לחפש אנשים, מקום, עבודה או שיתוף פעולה.</h2></article>`;
else if(r==='questions')x=`<section class="intro">${H('חיפוש · שאלה 1 מתוך 3','מה הכי קרוב למה שאת צריכה?')}</section><article class="card">${['משהו קיים','אנשים','מקום','עבודה'].map(z=>`<button class="filter" data-r="results">${z}</button>`).join('')}<button class="filter" data-r="no-results">לא בטוחה</button></article>`;
else if(r==='results')x=`<section class="intro">${H('תוצאות','מצאנו כמה כיוונים עבורך','אפשר לשמור את הצורך או לפרסם אותו — הבחירה שלך.')}</section><section class="feed">${card('initiative')}${card('place')}<article class="action-card">${H('Matching','רוצה שנעדכן אותך כשיימצא משהו חדש?')}${B('לשמור את החיפוש','save')}</article></section>`;
else if(r==='no-results')x=`<section class="intro">${H('אין התאמה כרגע','לא מצאנו משהו מדויק עדיין.','אפשר לבחור מה לעשות הלאה.')}</section><section class="feed">${B('לשמור ולעדכן אותי','save')}${B('לפרסם שאני מחפשת','draft')}${B('להרחיב את החיפוש','questions')}${B('לקבל רעיון מהשראה','inspiration')}</section>`;
else if(['initiative-detail','offer-detail','place-detail'].includes(r)){let k=r.split('-')[0],c=C[k];x=`<section class="intro">${H(c[0],c[1],c[2])}<div class="signals"><span>פרטי קשר רק בהסכמה הדדית</span></div>${B(k==='initiative'?'להגיש בקשת הצטרפות':'לבקש חיבור','connect')}</section><article class="card"><h2>מה קורה עכשיו?</h2><p>הפעולה תישלח לבדיקה. WhatsApp event: ${k==='initiative'?'join.requested':'connection.requested'}</p></article>`}
else if(r==='job')x=`<section class="intro">${H(C.job[0],C.job[1],C.job[2])}${B('למקור ולהגשה חיצונית','external')}</section><article class="card"><h2>External Application State</h2><p>אין מערכת ATS באתר.</p></article>`;
else if(r.startsWith('create'))x=`<section class="intro">${H('＋ להתחיל',r==='create-initiative'?'יצירת יוזמה':r==='create-offer'?'להציע משהו':'יש לי מקום')}</section><form class="card" id="form"><label>כותרת<input placeholder="איך לקרוא לזה?"></label><label>אזור או Online<input placeholder="פתח תקווה / Online"></label><label>תיאור<textarea placeholder="מה חשוב שידעו?"></textarea></label>${B('להמשיך לתצוגה מקדימה','preview')}</form>`;
else if(r==='preview')x=`<section class="intro">${H('לפני פרסום','ככה זה ייראה בפיד')}</section><article class="card featured"><h2>טיוטה חדשה</h2><p>הטיוטה עדיין לא פורסמה.</p>${B('לפרסם','publish')}</article>`;
else if(r==='manage')x=`<section class="intro">${H('ניהול יוזמה','היוזמה שלך','כמה צרכים פתוחים במקביל.')}</section><section class="feed">${['אנשים','מקום','אשת חינוך/טיפול'].map(z=>`<article class="card"><h2>${z}</h2><p>needed</p>${B('לבדוק התאמות','results')}</article>`).join('')}</section>`;
else if(r==='mine')x=`<section class="intro">${H('שלי','מה חשוב לך עכשיו?')}</section><section class="feed">${['מה שאני מחפשת','היוזמות שלי','מה שפרסמתי','החיבורים שלי'].map((z,i)=>`<article class="card"><h2>${z}</h2>${B('לפתוח',i?'manage':'saved')}</article>`).join('')}</section>`;
else if(r==='saved')x=`<section class="intro">${H('Saved Intent · פרטי','מה שאני מחפשת','Matching פעיל · עדכוני WhatsApp כבויים')}</section>${card('initiative')}<article class="card"><p>החיפוש הפרטי נשמר רק לאחר בחירה מפורשת.</p>${B('להפעיל עדכונים ב‑WhatsApp','whatsapp')}</article>`;
else if(r==='connect')x=`<section class="intro">${H('בקשה נשלחה','החיבור בתהליך','הצד השני תראה את הבקשה. פרטי קשר ייחשפו רק בהסכמה הדדית.')}</section><article class="card"><p>WhatsApp event: connection.requested</p>${B('לחזור לגלות','discover')}</article>`;
else if(r==='save-consent')x=`<section class="intro">${H('שמירת חיפוש','רק כדי לוודא','Saved Intent הוא צורך פרטי לצורך Matching ועדכונים — לא פוסט ציבורי.')}${B('כן, לשמור את החיפוש','save')}${B('לא עכשיו','results')}</section>`;
else if(r==='publish-success')x=`<section class="intro">${H('פורסם בהצלחה','היוזמה שלך באוויר','היא תופיע בפיד ותוכל לקבל התאמות.')}${B('לפתוח את היוזמה','initiative-detail')}${B('לשתף טקסט מוכן','actions')}</section>`;
else if(r==='whatsapp')x=`<section class="intro">${H('עדכוני WhatsApp','העדכון הופעל','תקבלי הודעה רק כשיש התאמה רלוונטית.')}</section><article class="card"><p>WhatsApp event: saved_intent.updates_enabled</p>${B('חזרה ל‑Saved Intent','saved')}</article>`;
else if(r==='recovery')x=`<section class="intro">${H('אין מקום מתאים','אפשר להמשיך מכאן')}</section><section class="feed">${B('להתחיל בבית עם שתי משפחות','create-initiative')}${B('לחפש פארק או מקום ציבורי','results')}${B('ליצור פנייה מוכנה','actions')}${B('לפרסם שאני מחפשת מקום','draft')}</section>`;
else if(r==='draft')x=`<section class="intro">${H('טיוטה שנוצרה מהחיפוש','פרסום מה אני מחפשת')}</section><article class="card"><h2>מחפשת משפחות לבקרים משותפים</h2><p>הטיוטה מבוססת על המידע שמסרת.</p>${B('לערוך ולפרסם','publish')}</article>`;
else if(r==='actions')x=`<section class="intro">${H('Done-for-you Action','הודעה מוכנה לשליחה')}</section><article class="card"><p>שלום, אני מחפשת לבדוק אפשרות לקבוצה קטנה של משפחות בבקרים. האם יש אצלכם מקום או גורם מתאים?</p>${B('העתקת הודעה','copy')}</article>`;
else if(r==='profile')x=`<section class="intro">${H('פרופיל והגדרות','החשבון שלי')}</section><article class="card"><p>מוצגים רק שם פרטי ואזור כללי.</p>${B('UX Flow Map','qa')}</article>`;
else if(r==='qa')x=`<section class="intro">${H('Internal QA','UX Flow Map','Browse → Item → Connect/Join → Account Gate → Confirmation')}</section><article class="card"><p>Search → Questions → Results / Partial / No Results → Save Intent או Prefilled Draft</p><p>Inspiration → Model → Create → Preview → Publish → Initiative</p><p>Need Place → Results → No Match → No-place Recovery</p><p>OPEN DECISION: שם ״שלי״; אימות חשבון; WhatsApp/Email.</p></article>`;A.innerHTML=x;bind()}
function bind(){document.querySelectorAll('[data-r]').forEach(e=>e.onclick=()=>{let r=e.dataset.r;if(r==='start')return start();if(['save','connect','publish'].includes(r)&&!S.login)return gate(r);S.r=r;page()});document.querySelector('#form')?.addEventListener('submit',e=>{e.preventDefault();S.r='preview';page()})}function start(){M.innerHTML=`<div class="scrim open"></div><section class="sheet open"><button class="close" data-close>×</button>${H('הצעד הראשון','מה היית רוצה לעשות?')}<div class="sheet-options"><button data-x="create-initiative">🌱 ליצור משהו</button><button data-x="search">🔎 למצוא משהו</button><button data-x="create-offer">✨ להציע משהו</button></div></section>`;M.querySelectorAll('[data-x]').forEach(e=>e.onclick=()=>{S.r=e.dataset.x;M.innerHTML='';page()});M.querySelector('[data-close]').onclick=()=>M.innerHTML=''}function gate(r){M.innerHTML=`<div class="scrim open"></div><section class="sheet open"><p class="eyebrow">Account Gate</p><h2>כדי לבצע את הפעולה צריך לפתוח חשבון.</h2><p>אחרי הכניסה נחזיר אותך בדיוק לאותה פעולה.</p>${B('הדגמת כניסה','login')}</section>`;M.querySelector('[data-r=login]').onclick=()=>{S.login=true;M.innerHTML='';S.r=r;page()}}page();
function bind(){document.querySelectorAll('[data-r]').forEach(e=>e.onclick=()=>{let r=e.dataset.r;if(r==='start')return start();if(['save','connect','publish'].includes(r)&&!S.login)return gate(r);if(r==='save')r='save-consent';if(r==='publish')r='publish-success';S.r=r;page()});document.querySelector('#form')?.addEventListener('submit',e=>{e.preventDefault();S.r='preview';page()})}page();
